language: python
cache: # caching is only available for customers who pay
    directories:
        - $HOME/.cache/pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
env:
    - DEBUG_MEMENTO_CLIENT=1

matrix:
  include:
    - python: '2.7_with_system_site_packages'
      dist: trusty
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - python2-requests
            - python2-lxml
            - python2-pytest
            - python2-pytest-xdist
      install: true

install:
    - "pip install requests"
    - "pip install lxml"
    - "pip install -U pytest pytest-xdist"
    - "pip install ."
script:
    - python setup.py test
    - python setup.py sdist bdist_wheel
