language: python
cache: # caching is only available for customers who pay
    directories:
        - $HOME/.cache/pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
env:
    - DEBUG_MEMENTO_CLIENT=1

matrix:
  include:
    - python: '2.7_with_system_site_packages'
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - python-requests
            - python-lxml
            - python-pytest
            - python-pytest-xdist
      install: true

install:
    - "pip install requests"
    - "pip install lxml"
    - "pip install -U pytest pytest-xdist"
    - "pip install ."
script:
    - pytest
